export enum EACTIONS {
    SHOW_LOGIN_DIALOG="SHOW_LOGIN_DIALOG", 
    CLOSE_LOGIN_DIALOG="CLOSE_LOGIN_DIALOG",

    LOGGED_IN="LOGGED_IN",
    LOGGED_OUT="LOGGED_OUT", 

    OPEN_APP_SIDEBAR="OPEN_APP_SIDEBAR",
    CLOSE_APP_SIDEBAR="CLOSE_APP_SIDEBAR",

    OPEN_FORGET_PASSWORD_DIALOG="OPEN_FORGET_PASSWORD_DIALOG",
    CLOSE_FORGET_PASSWROD_DIALOG="CLOSE_FORGET_PASSWROD_DIALOG",

    OPEN_SIGNUP_DIALOG = "OPEN_SIGNUP_DIALOG",
    CLOSE_SIGNUP_DIALOG="CLOSE_SIGNUP_DIALOG",

    CHANGE_APP_ROUTE="CHANGE_APP_ROUTE"
}