export enum EACTIONS {
    SHOW_LOGIN_DIALOG, 
    CLOSE_LOGIN_DIALOG,

    LOGGED_IN,
    LOGGED_OUT, 

    OPEN_APP_SIDEBAR,
    CLOSE_APP_SIDEBAR,

    OPEN_FORGET_PASSWORD_DIALOG,
    CLOSE_FORGET_PASSWROD_DIALOG
}